FROM python:3.9-slim

WORKDIR /app

# Instalar dependências do sistema
RUN apt-get update && apt-get install -y build-essential gcc && rm -rf /var/lib/apt/lists/*

# Copiar arquivos do projeto
COPY requirements.txt ./
COPY modelo-exportado-pipeline-autoai.pkl ./
COPY app.py ./

# Instalar dependências Python
RUN pip install --upgrade pip && pip install --no-cache-dir  --use-deprecated=legacy-resolver -r requirements.txt

EXPOSE 5000

CMD ["python", "app.py"]
